[metadata]
name = adop_manager
description = Adaptive Optics Script Manager
url = https://github.com/dls-controls/adop_manager
author = Ollie Copping
author_email = oliver.copping@diamond.ac.uk
license = Apache License 2.0
long_description = file: README.rst
long_description_content_type = text/x-rst
classifiers =
    Development Status :: 4 - Beta
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[options]
python_requires = >=3.10
packages = find:
# =src is interpreted as {"": "src"}
# as per recommendation here https://hynek.me/articles/testing-packaging/
package_dir =
    =src
    
# Specify any package dependencies below.
install_requires =
    numpy
    aioca
    softioc
    typer

[options.extras_require]
# For development tests/docs
dev =
    ruff
    pytest-cov
    sphinx-rtd-theme-github-versions
    pre-commit

[options.packages.find]
where = src

# Specify any package data to be included in the wheel below.
# [options.package_data]
# adop_manager =
#     subpackage/*.yaml

[options.entry_points]
# Include a command line script
console_scripts =
    adop_manager = adop_manager.__main__:main

[tool:pytest]
# Run pytest with all our checkers, and don't spam us with massive tracebacks on error
addopts =
    --tb=native -vv --doctest-modules --doctest-glob="*.rst"
    --cov=adop_manager --cov-report term --cov-report xml:cov.xml
# https://iscinumpy.gitlab.io/post/bound-version-constraints/#watch-for-warnings
filterwarnings = error
# Doctest python code in docs, python code in src docstrings, test functions in tests
testpaths =
    docs src tests

[coverage:run]
# This is covered in the versiongit test suite so exclude it here
omit = */_version_git.py
data_file = /tmp/adop_manager.coverage

[coverage:paths]
# Tests are run from installed location, map back to the src directory
source =
    src
    **/site-packages/
